/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    OverlayContent: typeof import('./components/OverlayContent.vue')['default']
    OverlayContent01: typeof import('./components/modal/OverlayContent01.vue')['default']
    OverlayContent02: typeof import('./components/modal/OverlayContent02.vue')['default']
    OverlayContent03: typeof import('./components/modal/OverlayContent03.vue')['default']
    OverlayContentWrapper: typeof import('./components/OverlayContentWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
