/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/draggable': RouteRecordInfo<'/draggable', '/draggable', Record<never, never>, Record<never, never>>,
    '/drawer': RouteRecordInfo<'/drawer', '/drawer', Record<never, never>, Record<never, never>>,
    '/overlaid': RouteRecordInfo<'/overlaid', '/overlaid', Record<never, never>, Record<never, never>>,
    '/sheets': RouteRecordInfo<'/sheets', '/sheets', Record<never, never>, Record<never, never>>,
    '/table-hover': RouteRecordInfo<'/table-hover', '/table-hover', Record<never, never>, Record<never, never>>,
    '/tabs': RouteRecordInfo<'/tabs', '/tabs', Record<never, never>, Record<never, never>>,
  }
}
